# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f79d62f6a2b9d573e100d80b3fa0bd8a"
name = "B2B Catalog2Collection"
handle = "b2b-app-19"
application_url = "https://tiles-recorders-democratic-aging.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "plus-b2b-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_product_listings,read_products,read_publications,write_product_listings,write_products,write_publications"

[auth]
redirect_urls = [
  "https://tiles-recorders-democratic-aging.trycloudflare.com/auth/callback",
  "https://tiles-recorders-democratic-aging.trycloudflare.com/auth/shopify/callback",
  "https://tiles-recorders-democratic-aging.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
